name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      HL2SDK_ROOT: "${{ github.workspace }}/external"
      MMS_PATH: "${{ github.workspace }}/external/metamod-source"
      MANIFEST_PATH: "${{ github.workspace }}/external/metamod-source/hl2sdk-manifests"
      CC: clang-14
      CXX: clang++-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -qy
          sudo apt-get install -y git clang-14 binutils python3 python3-pip zip
          python3 -m pip install --upgrade pip
          git clone https://github.com/alliedmodders/ambuild.git
          cd ambuild
          pip install .
          cd ..
          mkdir external
          cd external
          git clone --branch master --single-branch https://github.com/alliedmodders/metamod-source.git
          git -C metamod-source checkout 176bee4a8debb7625ab82c4059ac51809487278f
          git -C metamod-source submodule update --init --recursive
          git clone --branch cs2 --single-branch https://github.com/alliedmodders/hl2sdk.git hl2sdk-cs2
          git -C hl2sdk-cs2 checkout 7ae489c1722dfb117ff080d6403d85e01e9c53c9
          cd ..
          git clone https://github.com/pisex/SchemaEntity.git
          grep -rl NetworkStateChanged_t SchemaEntity | xargs -r sed -i 's/NetworkStateChanged_t/NetworkStateChangedData/g'

      - name: Build Core
        run: |
          cd Core
          mkdir -p build
          cd build
          python3 ../configure.py -s cs2 --targets x86_64 --enable-optimize --hl2sdk-manifests=$MANIFEST_PATH --mms_path=$MMS_PATH --hl2sdk-root=$HL2SDK_ROOT
          ambuild
          cd package
          zip -r Core.zip addons
          mv Core.zip ${{ github.workspace }}/Core.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Core
          path: ${{ github.workspace }}/Core.zip
